global:
  image:
    repository: cgr.dev/ky-rafaels.example.com/argocd
    tag: 3.0.11 
  # -- Secrets with credentials to pull images from a private registry
  # imagePullSecrets:
  #   - "regcred"
repoServer:
  image:
    repository: cgr.dev/ky-rafaels.example.com/argocd-repo-server
    tag: 3.0.11 
  # extraContainers:
  # - name: helm-plugin
  #   command: [/var/run/argocd/argocd-cmp-server]
  #   args: [--loglevel, debug]
  #   image: cgr.dev/ky-rafaels.example.com/custom-base
  #   securityContext:
  #     runAsNonRoot: true
  #     runAsUser: 999 # container already runs as nonroot by default 
  #   volumeMounts:
  #     - mountPath: /var/run/argocd
  #       name: var-files
  #     - mountPath: /home/argocd/cmp-server/plugins
  #       name: plugins
  #     - mountPath: /tmp
  #       name: cmp-tmp
      # - mountPath: /home/argocd/cmp-server/config/plugin.yaml
        # subPath: plugin.yaml
        # name: helm-plugin-config
  #     - name: oidc-token
  #       mountPath: /var/run/secrets/tokens
  volumes:
  - name: oidc-token
    projected:
      sources:
      - serviceAccountToken:
          path: oidc-token
          expirationSeconds: 3600
          audience: https://issuer.enforce.dev
  # - configMap:
  #     name: helm-plugin-config
  #   name: helm-plugin-config
  # - emptyDir: {}
  #   name: cmp-tmp
  # - emptyDir: {}
    # name: helm-plugin-tools
  volumeMounts:
    - name: oidc-token
      mountPath: /var/run/secrets/tokens
dex:
  image:
    repository: cgr.dev/ky-rafaels.example.com/dex
    tag: 2.42
redis:
  image:
    repository: cgr.dev/ky-rafaels.example.com/redis
    tag: 7.2.7
server:
  extraArgs:
  - --insecure
crds:
  install: true