apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-plugin-config 
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helm-oci-plugin
    spec:
      init:
        command: [sh, -c]
        args:
          - |
            cat /var/run/secrets/tokens/oidc-token | helm registry login \ 
              --username argocd-plugin \
              --password-stdin \
              $HELM_REGISTRY/$HELM_CHART_NAME
      generate:
        command: [sh, -c]
        args:
          - helm pull $HELM_REGISTRY/$HELM_CHART_NAME \
              --version $HELM_CHART_VERSION \
              --untar --untardir /tmp/chart
          - helm template $ARGOCD_APP_NAME /tmp/chart/$HELM_CHART_NAME \
              --namespace $ARGOCD_APP_NAMESPACE \
              --values <(echo "$ARGOCD_APP_VALUES")