apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-oci-plugin 
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helm-oci-plugin
    spec:
      init:
        command: [sh, -c]
        args:
          - |
            cat /var/run/secrets/tokens/oidc-token | helm registry login \ 
              --username argocd-plugin \
              --password-stdin \
              oci://cgr.dev/ky-rafaels.example.com/iamguarded-charts
      # generate:
      #   command: [sh, -c]
      #   args:
      #     - helm template $ARGOCD_APP_NAME /tmp/chart \
      #         --namespace $ARGOCD_APP_NAMESPACE \
      #         --values <(echo "$ARGOCD_APP_VALUES")
# helm pull oci://my-registry.io/my-chart \
#   --version $HELM_CHART_VERSION \
#   --untar --untardir /tmp/chart