apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: chainguard.dev
  namespace: cert-manager
spec:
  sources:
  # Include a bundle of publicly trusted certificates which can be
  # used to validate most TLS certificates on the internet
  - useDefaultCAs: true
  - secret:
      name: root-secret
      key: ca.crt
  target:
    configMap:
      key: "bundle.pem"
    additionalFormats:
      jks:
        key: "bundle.jks"
      pkcs12:
        key: "bundle.p12"
    namespaceSelector:
      matchLabels:
        create-certs: "true"