---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster 
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: cgr.dev/ky-rafaels.example.com/iamguarded-charts
    chart: redis-cluster 
    targetRevision: HEAD
    # plugin:
    #   name: helm-oci-plugin
    #   env: 
    #     - name: $HELM_REGISTRY
    #       value: oci://cgr.dev/ky-rafaels.example.com/iamguarded-charts
    #     - name: $HELM_CHART_NAME
    #       value: redis-cluster
    #     - name: $HELM_CHART_VERSION
    #       value: 12.0.1
    #   parameters:
    #     - name: helm-parameters
    #       map:
    #         global.org: ky-rafaels.example.com
    helm:
      passCredentials: true
      values: |
        global:
          org: ky-rafaels.example.com
  destination:
    name: "in-cluster"
    namespace: 'redis-cluster'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true