---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak 
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: oci://cgr.dev/ky-rafaels.example.com/iamguarded-charts/redis-cluster 
    chart: redis-cluster 
    targetRevision: 12.0.1
    plugin:
      name: helm-oci
      env: 
        - name: $HELM_REGISTRY
          value: oci://cgr.dev/ky-rafaels.example.com/iamguarded-charts
        - name: $HELM_CHART_NAME
          value: redis-cluster
        - name: $HELM_CHART_VERSION
          value: 12.0.1
    helm:
      ignoreMissingValueFiles: true
      values: |
        global:
          org: ky-rafaels.example.com
  destination:
    name: "in-cluster"
    namespace: 'redis-cluster'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true