---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: default
spec:
  secretName: wildcard-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: 'wildcard'
  subject:
    organizations:
      - chainguard
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - '*.ky-rafaels.com'
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: keystore-pass
        key: password